package com.isaac.stock.entities;
// Generated Jun 3, 2020 7:18:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblStockHistory generated by hbm2java
 */
@Entity
@Table(name = "tbl_stock_history", catalog = "card_gateway")
public class TblStockHistory implements java.io.Serializable {

	private Long rowId;
	private String regDate;
	private String stockCode;
	private Double openPrice;
	private Double closePrice;
	private Double lowPrice;
	private Double highPrice;
	private Double volume;

	public TblStockHistory() {
	}

	public TblStockHistory(String regDate, String stockCode, Double openPrice, Double closePrice, Double lowPrice,
			Double highPrice, Double volume) {
		this.regDate = regDate;
		this.stockCode = stockCode;
		this.openPrice = openPrice;
		this.closePrice = closePrice;
		this.lowPrice = lowPrice;
		this.highPrice = highPrice;
		this.volume = volume;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public Long getRowId() {
		return this.rowId;
	}

	public void setRowId(Long rowId) {
		this.rowId = rowId;
	}

	@Column(name = "reg_date", length = 20)
	public String getRegDate() {
		return this.regDate;
	}

	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}

	@Column(name = "stock_code", length = 50)
	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	@Column(name = "open_price", precision = 22, scale = 0)
	public Double getOpenPrice() {
		return this.openPrice;
	}

	public void setOpenPrice(Double openPrice) {
		this.openPrice = openPrice;
	}

	@Column(name = "close_price", precision = 22, scale = 0)
	public Double getClosePrice() {
		return this.closePrice;
	}

	public void setClosePrice(Double closePrice) {
		this.closePrice = closePrice;
	}

	@Column(name = "low_price", precision = 22, scale = 0)
	public Double getLowPrice() {
		return this.lowPrice;
	}

	public void setLowPrice(Double lowPrice) {
		this.lowPrice = lowPrice;
	}

	@Column(name = "high_price", precision = 22, scale = 0)
	public Double getHighPrice() {
		return this.highPrice;
	}

	public void setHighPrice(Double highPrice) {
		this.highPrice = highPrice;
	}

	@Column(name = "volume", precision = 22, scale = 0)
	public Double getVolume() {
		return this.volume;
	}

	public void setVolume(Double volume) {
		this.volume = volume;
	}

}
